# azure-pipelines.yml
trigger:
- master

resources:
  containers:
  - container: 'iast_agent_server'
    image: 'veracode/iast-agent-server:latest'
    env:
      VERACODE_API_KEY_ID: $veracode_api_key_id
      VERACODE_API_KEY_SECRET: $veracode_api_key_secret
    ports:
    - 10010:10010

jobs:
- job: run_iast_agent_server
  displayName: Run the IAST Agent Server

  pool:
    vmImage: 'ubuntu-latest'

  services:
    iast_agent_server: iast_agent_server

  steps:
  - script: |
      echo Waiting for Agent Server to start
      sleep 60
      curl --insecure https://iast_agent_server:10010/iast/as/v1
    displayName: Ping Agent Server

  - script: echo Sending session_start event
    displayName: Send session_start event

  - script: echo Building solution...
    displayName: Build

  - script: echo Testing with IAST...
    displayName: Test

  - script: echo Sending session_stop event...
    displayName: Send session_stop event

  - script: echo Getting results...
    displayName: Get results