# azure-pipelines.yml
trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  AGENT_SERVER_URL:'https://localhost:10010/iast/as/v1'

resources:
  containers:
  - container: 'iast_agent_server'
    image: 'veracode/iast-agent-server:latest'
    options: -e VERACODE_API_KEY_ID=$(api_key_id) -e VERACODE_API_KEY_SECRET=$(api_key_secret)
    ports:
    - 10010:10010

stages:
- stage: main
  pool: 
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Run_Agent_Server
    services:
      iast_agent_server: iast_agent_server
    pool:
      vmImage: 'windows-2019'
    steps: 
    - task: AzurePowerShell@5
    - powershell: |
        Write-Host "Waiting for Agent Server to start"
        $webRequest = [Net.WebRequest]::Create('$(AGENT_SERVER_URL)')
        try { $webRequest.GetResponse() } catch {}
        $cert = $webRequest.ServicePoint.Certificate
        $bytes = $cert.Export("Cert")
        set-content -value $bytes -encoding byte -path "$pwd\Agent-Server.cert"
        Import-Certificate -FilePath $pwd\Agent-Server.cert -CertStoreLocation Cert:\LocalMachine\Root\
      displayName: Ping Agent Server
  - job: Nuget
    pool:
      vmImage: 'windows-2019'
    steps: 
    - bash: |
        echo "nuget"
      displayName: Nuget
  - job: Build
    pool:
      vmImage: 'windows-2019'
    steps: 
    - bash: |
        echo "build"
      displayName: Build
  - job: test_iast
    pool:
      vmImage: 'windows-2019'
    steps: 
    - bash: |
        echo "test"
      displayName: Test
  - job: session_stop
  - job: get_results