# azure-pipelines.yml
trigger:
- master

resources:
  containers:
  - container: 'iast_agent_server'
    properties:
      environmentVariables:
        - name: 'VERACODE_API_KEY_ID'
          value: $(api_key_id)
        - name: 'VERACODE_API_KEY_SECRET'
          secureValue: $(api_key_secret)
    image: 'veracode/iast-agent-server:latest'
    ports:
    - 10010:10010

jobs:
- job: run_iast_agent_server
  displayName: Run the IAST Agent Server

  pool:
    vmImage: 'ubuntu-latest'

  services:
    iast_agent_server: iast_agent_server
  steps:
  - script: |
      echo 'Waiting for Agent Server to start'
      echo "my pipeline variable is: $VERACODE_API_KEY_ID"
      sleep 30
      DEBUG=1 curl -k -L https://iast_agent_server:10010/iast/as/v1
    displayName: Ping Agent Server

  - script: echo Sending session_start event
    displayName: Send session_start event

  - script: echo Building solution...
    displayName: Build

  - script: echo Testing with IAST...
    displayName: Test

  - script: echo Sending session_stop event...
    displayName: Send session_stop event

  - script: echo Getting results...
    displayName: Get results