# azure-pipelines.yml
trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

resources:
  containers:
  - container: 'iast_agent_server'
    image: 'veracode/iast-agent-server:latest'
    options: -e VERACODE_API_KEY_ID=$(api_key_id) -e VERACODE_API_KEY_SECRET=$(api_key_secret)
    ports:
    - 10010:10010

stages:
- stage: main
  pool: 
    vmImage: 'windows-2019'
  jobs:
  - job: Run_Agent_Server
    services:
      iast_agent_server: iast_agent_server
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - bash: |
        echo "Waiting for Agent Server to start"
        sleep 30
        DEBUG=1 curl -k -L https://localhost:10010/iast/as/v1
        sleep 5
        echo "Downloading agents..."
        DEBUG=1 curl -k -L https://localhost:10010/iast/as/v1/downloads | sh
        ls -la
      displayName: Ping Agent Server
  - job: Nuget_Install
    pool:
      vmImage: 'windows-2019'
    steps: 
    - task: NuGetToolInstaller@1
    - bash: |
        echo "Installing nuget..."
      displayName: Nuget Install
  - job: Run_Nuget
    pool:
      vmImage: 'windows-2019'
    steps: 
    - task: NuGetCommand@2
    - bash: |
        echo "Running nuget"
      displayName: Nuget Run
  - job: Build
    pool:
      vmImage: 'windows-2019'
    steps: 
    - bash: |
        echo "build"
      displayName: Build
  - job: test_iast
    pool:
      vmImage: 'windows-2019'
    steps: 
    - bash: |
        echo "test"
      displayName: Test
  - job: session_stop
  - job: get_results