# azure-pipelines.yml
trigger:
- master

variables:
- name: VERACODE_API_KEY_ID
  value: $(api_key_id)
- name: VERACODE_API_KEY_SECRET
  value: $(api_key_secret)

resources:
  containers:
  - container: 'iast_agent_server'
    image: 'veracode/iast-agent-server:latest'
    options: -e VERACODE_API_KEY_ID=$(api_key_id) -e VERACODE_API_KEY_SECRET=$(api_key_secret)
    ports:
    - 10010:10010

stages:
- stage: main
  pool: 
    vmImage: 'windows-2019'
  jobs:
  - job: Run_Agent_Server
    services:
      iast_agent_server: iast_agent_server
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - task: AzurePowerShell@5
      inputs:
        azurePowerShellVersion: latestVersion
    - powershell: |
        Write-Host "Waiting for Agent Server to start"
        sleep 30
        if (-not ([System.Management.Automation.PSTypeName]'ServerCertificateValidationCallback').Type)
        {
        $certCallback = @"
            using System;
            using System.Net;
            using System.Net.Security;
            using System.Security.Cryptography.X509Certificates;
            public class ServerCertificateValidationCallback
            {
                public static void Ignore()
                {
                    if(ServicePointManager.ServerCertificateValidationCallback ==null)
                    {
                        ServicePointManager.ServerCertificateValidationCallback += 
                            delegate
                            (
                                Object obj, 
                                X509Certificate certificate, 
                                X509Chain chain, 
                                SslPolicyErrors errors
                            )
                            {
                                return true;
                            };
                    }
                }
            }
        "@
            Add-Type $certCallback
        }
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
        [ServerCertificateValidationCallback]::Ignore()
        Invoke-WebRequest -Uri https://localhost:10010/iast/as/v1
      displayName: Ping Agent Server