# azure-pipelines.yml
trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

resources:
  containers:
  - container: 'iast_agent_server'
    image: 'veracode/iast-agent-server:latest'
    options: -e VERACODE_API_KEY_ID=$(api_key_id) -e VERACODE_API_KEY_SECRET=$(api_key_secret)
    ports:
    - 10010:10010

stages:
- stage: main
  pool: 
    vmImage: 'windows-2019'
  jobs:
  - job: Run_Agent_Server
    services:
      iast_agent_server: iast_agent_server
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - powershell: |
        Write-Host "Waiting for Agent Server to start"
        Invoke-RestMethod -Uri "https://localhost:10010/iast/as/v1"
      displayName: Ping Agent Server
  - job: Nuget_Install
    pool:
      vmImage: 'windows-2019'
    steps: 
    - task: NuGetToolInstaller@1
  - job: nuget
    pool:
      vmImage: 'windows-2019'
    steps: 
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
  - job: build
    pool:
      vmImage: 'windows-2019'
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
  - job: test
    pool:
      vmImage: 'windows-2019'
    steps: 
    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        otherConsoleOptions: '/Framework:.NETFramework,Version=v4.7.2'