# azure-pipelines.yml
trigger:
- master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

resources:
  containers:
  - container: 'iast_agent_server'
    image: 'veracode/iast-agent-server:latest'
    options: -e VERACODE_API_KEY_ID=$(api_key_id) -e VERACODE_API_KEY_SECRET=$(api_key_secret)
    ports:
    - 10010:10010

stages:
- stage: main
  pool: 
    vmImage: 'windows-2019'
  jobs:
  - job: Run_Agent_Server
    services:
      iast_agent_server: iast_agent_server
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - bash: |
        echo "Waiting for Agent Server to start"
        sleep 30
        DEBUG=1 curl -k -L https://localhost:10010/iast/as/v1
        sleep 5
        echo "Downloading agents..."
        DEBUG=1 curl -k -L https://localhost:10010/iast/as/v1/downloads | sh
        ls -la
      displayName: Run Agent Server
  - job: Nuget_Build
    pool:
      vmImage: 'windows-2019'
    steps: 
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
  - job: test_iast
    pool:
      vmImage: 'windows-2019'
    steps: 
    - bash: |
        echo "setting COR profiler"
        SET COR_ENABLE_PROFILING=1
        SET COR_PROFILER={90747D54-A553-4353-8E39-CA9ADE930151}
        SET COR_PROFILER_PATH=agent_dotnet_win32.dll
      displayName: Test
  - job: session_stop
  - job: get_results