# azure-pipelines.yml
trigger:
- master

variables:
- name: VERACODE_API_KEY_ID
  value: $(api_key_id)
- name: VERACODE_API_KEY_SECRET
  value: $(api_key_secret)

resources:
  containers:
  - container: 'iast_agent_server'
    image: 'veracode/iast-agent-server:latest'
    options: -e VERACODE_API_KEY_ID=$(api_key_id) -e VERACODE_API_KEY_SECRET=$(api_key_secret)
    ports:
    - 10010:10010

stages:
- stage: main
  pool: 
    vmImage: 'windows-2019'
  jobs:
  - job: Run_Agent_Server
    services:
      iast_agent_server: iast_agent_server
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - powershell: |
        Write-Host "Waiting for Agent Server to start"
        Function ReturnTrue()
        {
          return $true
        }
        [System.Net.ServicePointManager]::ServerCertificateValidationCallback =  ReturnTrue
        Invoke-WebRequest -Uri "https://localhost:10010/iast/as/v1"
      displayName: Ping Agent Server